using System;
using System.Collections.Generic;
using System.Text;

namespace LineageServer.Enum
{
    /// <summary>
    /// 資料庫所有Table
    /// </summary>
    enum DataSourceTypeEnum : byte
    {
        Table_accounts,
        Table_area,
        Table_armor,
        Table_armor_set,
        Table_ban_ip,
        Table_beginner,
        Table_board,
        Table_board_auction,
        Table_castle,
        Table_characters,
        Table_character_buddys,
        Table_character_buff,
        Table_character_config,
        Table_character_elf_warehouse,
        Table_character_items,
        Table_character_quests,
        Table_character_skills,
        Table_character_teleport,
        Table_character_warehouse,
        Table_clan_data,
        Table_clan_members,
        Table_clan_recommend_apply,
        Table_clan_recommend_record,
        Table_clan_warehouse,
        Table_clan_warehouse_history,
        Table_commands,
        Table_connection_test_table,
        Table_door_gfxs,
        Table_droplist,
        Table_drop_item,
        Table_dungeon,
        Table_dungeon_random,
        Table_etcitem,
        Table_furniture_item,
        Table_getback,
        Table_getback_restart,
        Table_house,
        Table_inn,
        Table_inn_key,
        Table_letter,
        Table_log_chat,
        Table_log_enchant,
        Table_magic_doll,
        Table_mail,
        Table_mapids,
        Table_mobgroup,
        Table_mobskill,
        Table_npc,
        Table_npcaction,
        Table_npcchat,
        Table_petitem,
        Table_pets,
        Table_pettypes,
        Table_polymorphs,
        Table_race_ticket,
        Table_resolvent,
        Table_shop,
        Table_skills,
        Table_spawnlist,
        Table_spawnlist_boss,
        Table_spawnlist_door,
        Table_spawnlist_furniture,
        Table_spawnlist_light,
        Table_spawnlist_npc,
        Table_spawnlist_time,
        Table_spawnlist_trap,
        Table_spawnlist_ub,
        Table_spr_action,
        Table_town,
        Table_trap,
        Table_ub_managers,
        Table_ub_settings,
        Table_ub_times,
        Table_weapon,
        Table_weapon_skill,
        Table_william_item_price,
        Table_william_level,
    }
}
